### PR TITLE
update readme and gitignore to account for virtualenv and settings.ini

### PR DESCRIPTION
**Pull request by EMCain**
I updated the readme to contain instructions for setting up a virtualenv. 

I also added the virtualenv folder and `settings.ini` to the .gitignore.

### CODE REVIEW

**Comment by shimpossible** [comment]
Are you sure python 3 works?

**Comment by EMCain** [comment]
No. How would I test it? Is the only way to set up a Slack API token and send a test message to an existing channel?

**Comment by EMCain** [comment]
Also--should it be changed to Python 2? Do you know what version it was written in?

**Comment by shimpossible** [comment]
I dont know what it was written for.  I'm using python 2.7 and it works. It was just a lucky guess..

You can set slack channel to your name
SLACK_CHANNEL=shimpossible

and it will post messages to you.  You have to already have the chat open with the person though.  And since everyone has a chat open with themselves this should work.

**Pull request merged**
